---
title: "Chicago Crime and Safety"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(here)
library(stringr)
library(knitr)
library(ggcorrplot)
library(ggmap)
library(sf)
library(Cairo)

source("../../theme.R")
windows.options(antialias = "cleartype")
options(device = Cairo::CairoWin)

knitr::opts_chunk$set(echo = TRUE,fig.width=10, fig.height=7, dev = "cairo_pdf", tidy.opts=list(width.cutoff=60), tidy=TRUE)

```

## Background

## About the Data
```{r import-data, echo=FALSE, cache=TRUE}
chi_crime_data = readRDS(here("Data", "chi_crime_data_cleaned.rds"))
chi_crime_data$Beat = chi_crime_data$Beat %>% as.numeric()
chi_crime_data$District = chi_crime_data$District %>% as.numeric()
chi_crime_data = chi_crime_data %>% bind_cols(as_tibble(st_coordinates(chi_crime_data)))

data_sample = chi_crime_data %>% head(5) 
data_sample$Date = as.character(data_sample$Date)
#data_sample %>% kable(format = "markdown")

num_obs= chi_crime_data$ID %>% length()
num_vars = chi_crime_data[1,] %>% unlist() %>% length()
```
The data set has `r num_obs` observations and `r num_vars` variables.

## Descriptive Statistics 
```{r corr-plot, echo=FALSE, cache=TRUE}
excluded_vars = c("ID", "Case Number", "Block", "IUCR", "Primary Type", "Description", "Location Description", "FBI Code", "X Coordinate", "Y Coordinate", "Updated On", "Location", "Historical Wards 2003-2015", "Community Areas", "geometry", "X", "Y")
cor_matrix = chi_crime_data %>% select(-excluded_vars) %>% st_drop_geometry() %>% mutate_all(function(x) as.numeric(x)) %>% na.omit() %>% cor() %>% round(1)
prob_mat = chi_crime_data %>% select(-excluded_vars) %>% st_drop_geometry() %>% mutate_all(function(x) as.numeric(x)) %>% na.omit() %>% cor_pmat()
ggcorrplot(cor_matrix, p.mat = prob_mat, hc.order = TRUE,
    type = "lower", insig = "blank", lab = TRUE, colors = color_pal(3)) + theme_master() + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + labs(title = "Few Correlations In Chicago Crime Data" , legend = "Correlation", x = "", y = "")
```

```{r time-series-total, echo=FALSE, cache=TRUE}
counts_by_day = chi_crime_data$Date %>% table() %>% as_tibble()
names(counts_by_day) = c("Date", "Count")
counts_by_day$Date = as.Date(counts_by_day$Date)
counts_by_day = counts_by_day %>% full_join(tibble(`Date` = chi_crime_data$Date, `Year` = chi_crime_data$Year))
counts_by_day$Year = factor(counts_by_day$Year)
counts_by_day %>% ggplot(aes(x = Date, y = Count)) + geom_line(color = "grey70") + geom_smooth(aes(fill = Year, color = Year), size = 2) + scale_color_manual(values = color_pal(5, "continuous")) + scale_fill_manual(values = color_pal(5, "continuous")) + theme_master() + labs(title = "Strong Seasonal Effect in Total Chicago Crimes", subtitle = "More crimes are reported during the summer and around the start of the year", x = "Year", y = "Crimes Reported Daily") + theme(panel.grid.minor.x = element_blank()) + hide_legend 
```
```{r time-series-facet, echo=FALSE, cache=TRUE}
counts_by_day = chi_crime_data %>% .$Date %>% table() %>% as_tibble()
names(counts_by_day) = c("Date", "Total")
for (cat in c('Night', '`Violent Crime`', 'Domestic', 'Arrest', '`In Vehicle`', '`In Building`')) {
  temp = chi_crime_data %>% filter(eval(parse(text = paste(cat)))) %>% .$`Date` %>% table() %>% as_tibble() 
  names(temp) = c("Date", cat)
  counts_by_day = left_join(counts_by_day, temp)
}
counts_by_day$Date = as.Date(counts_by_day$Date)
counts_by_day = counts_by_day %>% full_join(tibble(`Date` = chi_crime_data$Date, `Year` = chi_crime_data$Year))
counts_by_day$Year = factor(counts_by_day$Year)
counts_by_day = counts_by_day %>% gather("Category", "Value", -Date, -Year, -Total)

counts_by_day %>% ggplot(aes(x = Date, y = Value)) + geom_line(color = "grey70") + geom_smooth(aes(fill = Year, color = Year), size = 1.5) + scale_color_manual(values = color_pal(5, "continuous")) + scale_fill_manual(values = color_pal(5, "continuous")) + facet_wrap(~Category, scales = "free") + theme_master() + labs(title = "Arrests are the Only Category Decrease Since 2014", subtitle = "While consistent overall, domestic crimes and crimes that happened at night or in a building spiked during the holidays", x = "Year", y = "Crimes Reported Daily") + theme(panel.grid.minor.x = element_blank(), panel.grid.major.x = element_blank()) + hide_legend 
```

```{r time-series-category, echo=FALSE, cache=TRUE}
counts_by_year = tibble(Category = character(), . = numeric(), n = numeric())
chi_crime_data$Total = TRUE

for (cat in c('Total', '`Violent Crime`', 'Domestic', 'Arrest', '`In Vehicle`', '`In Building`')) {
  temp = chi_crime_data %>% filter(eval(parse(text = paste(cat)))) %>% .$Year %>% table() %>% as_tibble() 
  temp$Category = cat
  temp_n = temp$n
  for (i in 2:5) {
    temp$n[i] = (temp_n[i] - temp_n[i - 1]) / temp_n[i - 1]
    
  }
  counts_by_year = temp[2:5, ] %>% bind_rows(counts_by_year)
}
names(counts_by_year) = c("Year", "Counts", "Category")
counts_by_year$Year = as.numeric(counts_by_year$Year)

counts_by_year %>% ggplot(aes(x = Year, y = Counts, color = Category)) + geom_line(size = 1.5) + geom_point(size = 2) + scale_y_continuous(labels = scales::percent_format(accuracy = 1)) + scale_color_manual(values = color_pal(6)) + theme_master() + labs(title = "Arrests Fell Significantly More than Reported Crimes in 2015", subtitle = "While reports of domestic crime have continually increased, other crimes dipped in 2014 and 2015 before increasing again after 2016", y = "Percent Change From Previous Year")
```


## Geospatial Analysis
```{r map-setup, echo=FALSE, cache=TRUE}
# get b&W map
chi_map <- ggmap(get_map(center = c(lon = -87.6298, lat = 41.8781), scale = 2, zoom = 10, maptype = "toner"))
```

```{r total-heatmap, echo=FALSE, cache=TRUE}
chi_map_data = tibble(ID = chi_crime_data$`ID`, X = chi_crime_data$X, Y = chi_crime_data$Y) %>% left_join(chi_crime_data[c(1,8, 14:18)]) %>% filter(Y > -87.8 & Y < -87.5) %>% filter(X > 41.65 & X < 42.05)

facet_data = gather(chi_map_data, "Category", "Value", -ID, -X, -Y, -geometry) %>% filter(Value) %>% .[1:5]


chi_map + stat_density2d(data = chi_map_data, aes(x = Y, y = X, fill=stat(level)), geom="polygon", alpha = 0.75) +  scale_fill_gradientn(colors = color_pal(5, "continuous", reverse = TRUE)) + scale_y_continuous(limits = c(41.65, 42.05)) + theme_map() + theme(legend.position = "right") + labs(title = "Chicago Crimes Follow Population Density")

chi_map + stat_density2d(data = facet_data, aes(x = Y, y = X, fill=stat(level)), geom="polygon", alpha = 0.75) + facet_wrap(~Category) + scale_fill_gradientn(colors = color_pal(5, "continuous", reverse = TRUE)) + scale_y_continuous(limits = c(41.65, 42.05)) + theme_map() + theme(legend.position = "right") + labs(title = "Reports of Arrests and Domestic Crimes More Likely on West Side")
```

```{r community-areas, echo=FALSE, cache=TRUE}
chi_map_cas = chi_crime_data$`Community Area` %>% table() %>% as_tibble() 
names(chi_map_cas) = c("ID", "n_crimes")
for (cat in c('Night', '`Violent Crime`', 'Domestic', 'Arrest', '`In Vehicle`', '`In Building`')) {
  temp = chi_crime_data %>% filter(eval(parse(text = paste(cat)))) %>% .$`Community Area` %>% table() %>% as_tibble() 
  names(temp) = c("ID", cat)
  chi_map_cas = left_join(chi_map_cas, temp)
}
chi_map_cas$ID = as.numeric(chi_map_cas$ID)
chi_map_cas = chi_map_cas %>% filter(ID != 0)
chi_map_cas = chi_map_cas %>% left_join(read_csv(here("Data", "2016Demo.csv")))
chi_cas_geom = read_sf(here("Data", "Chicago_Communities_Shp", "chi_comms.shp"))[c(3,8,9,10)]
names(chi_cas_geom) = c("ID", "shape_area", "shape_len", "geometry")
chi_cas_geom$ID = as.numeric(chi_cas_geom$ID)
chi_map_cas = chi_map_cas %>% left_join(chi_cas_geom)
chi_map_cas = chi_map_cas %>% st_as_sf()



excluded_vars = c("ID", "GEOG", "WHITE", "HISP", "BLACK", "ASIAN", "OTHER", "geometry")
cor_matrix = chi_map_cas %>% select(-excluded_vars) %>% mutate_all(function(x) as.numeric(x)) %>% na.omit() %>% cor() %>% round(1)
prob_mat = chi_map_cas %>% select(-excluded_vars)  %>% mutate_all(function(x) as.numeric(x)) %>% na.omit() %>% cor_pmat()
ggcorrplot(cor_matrix, p.mat = prob_mat, hc.order = TRUE,
    type = "lower", insig = "blank", lab = TRUE, colors = color_pal(3)) + theme_master() + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + labs(title = "Reported Crimes Weakly Correlated with Race and Community Area Size", subtitle = "A higher percentage of blacks in a community area and community areas that are larger geographically accompany a rise in total crimes", legend = "Correlation", x = "", y = "")

chi_map + geom_sf(data = chi_map_cas, aes(geometry = geometry, fill=(n_crimes / TOT_POP)), alpha = 0.75, inherit.aes = FALSE) + scale_fill_gradientn(colors = color_pal(5, "continuous", reverse = TRUE)) + scale_y_continuous(limits = c(41.65, 42.05)) + theme_map() + theme(legend.position = "right") + labs(title = "More Crimes per Capita on South and West Sides", subtitle = "While there still exists a high concentration of crimes per capita in the Loop, the worst neighborhoods are elsewhere", fill = "Reported Crimes \nper Capita")

facet_data = chi_map_cas[c(1, 3:8,10, 23)] %>% gather("Category", "Value", -ID, -TOT_POP, -geometry)

chi_map + geom_sf(data = facet_data, aes(geometry = geometry, fill=(Value / TOT_POP)), alpha = 0.75, inherit.aes = FALSE) + facet_wrap(~Category) + scale_fill_gradientn(colors = color_pal(5, "continuous", reverse = TRUE)) + scale_y_continuous(limits = c(41.65, 42.05)) + theme_map() + theme(legend.position = "right") + labs(title = "More Crimes per Capita on South and West Sides", subtitle = "While there still exists a high concentration of crimes per capita in the Loop, the worst neighborhoods are elsewhere", fill = "Reported Crimes \nper Capita") + theme_map() + theme(legend.position = "right")

```

## Conclusion
